### ISSUE TITLE
 seconds (IMPORT FAILED): C:\ComfyUI\custom_nodes\comfyui_face_parsing

### ISSUE THREAD

**Issue by ORIGINAI6** [Ryuukeisyou/comfyui_face_parsing#20]
Hello author, this plugin is not compatible with the latest version
pytorch version: 2.4.1+cu124
xformers version: 0.0.28.post
This version can significantly improve inference speed, but unfortunately your plugin does not support it. We hope to update it as soon as possible
![Snipaste_2024-09-28_10-10-09](https://github.com/user-attachments/assets/e9b350af-bd6d-4f2d-9a8f-06d4a6007dd0)
![Snipaste_2024-09-28_10-10-43](https://github.com/user-attachments/assets/3ca3d5dc-b2fc-4003-acc8-db5705d2f032)

**Comment by Ryuukeisyou** [comment]
hi, can you provide error printed in the console?

**Comment by bananasss00** [comment]
> hi, can you provide error printed in the console?

```
Traceback (most recent call last):
  File "V:\comfyu_py311\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "V:\comfyu_py311\ComfyUI\custom_nodes\comfyui_face_parsing\__init__.py", line 16, in <module>
    download_url("https://huggingface.co/jonathandinu/face-parsing/resolve/main/model.safetensors?download=true", face_parsing_path, "model.safetensors")
  File "V:\comfyu_py311\python_embeded\Lib\site-packages\torchvision\datasets\utils.py", line 122, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "V:\comfyu_py311\python_embeded\Lib\site-packages\torchvision\datasets\utils.py", line 66, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "urllib\request.py", line 216, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 634, in http_response
  File "urllib\request.py", line 557, in error
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 749, in http_error_302
  File "urllib\request.py", line 519, in open
  File "urllib\request.py", line 536, in _open
  File "urllib\request.py", line 496, in _call_chain
  File "urllib\request.py", line 1391, in https_open
  File "urllib\request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>

Cannot import V:\comfyu_py311\ComfyUI\custom_nodes\comfyui_face_parsing module for custom nodes: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
```

**Comment by Ryuukeisyou** [comment]
> > hi, can you provide error printed in the console?
> 
> ```
> Traceback (most recent call last):
>   File "V:\comfyu_py311\ComfyUI\nodes.py", line 1998, in load_custom_node
>     module_spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "V:\comfyu_py311\ComfyUI\custom_nodes\comfyui_face_parsing\__init__.py", line 16, in <module>
>     download_url("https://huggingface.co/jonathandinu/face-parsing/resolve/main/model.safetensors?download=true", face_parsing_path, "model.safetensors")
>   File "V:\comfyu_py311\python_embeded\Lib\site-packages\torchvision\datasets\utils.py", line 122, in download_url
>     url = _get_redirect_url(url, max_hops=max_redirect_hops)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "V:\comfyu_py311\python_embeded\Lib\site-packages\torchvision\datasets\utils.py", line 66, in _get_redirect_url
>     with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "urllib\request.py", line 216, in urlopen
>   File "urllib\request.py", line 525, in open
>   File "urllib\request.py", line 634, in http_response
>   File "urllib\request.py", line 557, in error
>   File "urllib\request.py", line 496, in _call_chain
>   File "urllib\request.py", line 749, in http_error_302
>   File "urllib\request.py", line 519, in open
>   File "urllib\request.py", line 536, in _open
>   File "urllib\request.py", line 496, in _call_chain
>   File "urllib\request.py", line 1391, in https_open
>   File "urllib\request.py", line 1351, in do_open
> urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
> 
> Cannot import V:\comfyu_py311\ComfyUI\custom_nodes\comfyui_face_parsing module for custom nodes: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)>
> ```

seems like you cannot download from huggingface. you can follow readme to download the models mannually and put them in correct locations.
