### ISSUE TITLE
FaceBBoxDetectorLoader(FaceParsing)

### ISSUE THREAD

**Issue by viklen30** [Ryuukeisyou/comfyui_face_parsing#6]
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\NTest\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'FaceBBoxDetectorLoader(FaceParsing)' node.
Traceback (most recent call last):
  File "D:\NTest\ComfyUI\ComfyUI\server.py", line 414, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\NTest\ComfyUI\ComfyUI\server.py", line 392, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NTest\ComfyUI\ComfyUI\custom_nodes\comfyui_face_parsing\face_parsing_nodes.py", line 24, in INPUT_TYPES
    files = folder_paths.get_filename_list("ultralytics_bbox")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NTest\ComfyUI\ComfyUI\folder_paths.py", line 220, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\NTest\ComfyUI\ComfyUI\folder_paths.py", line 187, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'ultralytics_bbox'

**Comment by ssm82** [comment]
Installing the Impact-Pack extension solved the problem

**Comment by Ryuukeisyou** [comment]
with new commit now make dir will be excuted before downloading the file. hope this fix the problem.

**Comment by Sinitra** [comment]
> Installing the Impact-Pack extension solved the problem

ssm82 May the most beautiful women in the world adore your balls. 😁👍❤️

**Comment by Aries2003** [comment]
Impact-Pack extension didnt solved the problem for me

**Comment by S0LTIS** [comment]
It's Renamed BBox not FaceBBox. Look in node list.
